version: '3.3'

services:

  app:
    image: ${IMAGE:-app}
    ports:
      - "8080:8080"  
    depends_on:
      - mongo
      - prometheus
      - pushgateway
    environment:
      - HTTP_ENABLED=true
      - HTTP_PORT=8080
      - MONGO_ENABLED=true
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017

      - PROMETHEUS_SERVICE_HOST=prometheus
      - PROMETHEUS_SERVICE_PORT=9090
      - PUSHGATEWAY_METRICS_SERVICE_HOST=pushgateway
      - PUSHGATEWAY_METRICS_SERVICE_PORT=9091
      - PUSHGATEWAY_METRICS_ENABLED=true

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
